#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  -- Auth
  CREATE USER ${POSTGRES_AUTH_USER:-tt_auth} WITH PASSWORD '${POSTGRES_AUTH_PASSWORD:-tt_auth_password}';
  CREATE DATABASE ${POSTGRES_AUTH_DB:-tt_auth} OWNER ${POSTGRES_AUTH_USER:-tt_auth};

  -- Members
  CREATE USER ${POSTGRES_MEMBERS_USER:-tt_members} WITH PASSWORD '${POSTGRES_MEMBERS_PASSWORD:-tt_members_password}';
  CREATE DATABASE ${POSTGRES_MEMBERS_DB:-tt_members} OWNER ${POSTGRES_MEMBERS_USER:-tt_members};

  -- Agenda
  CREATE USER ${POSTGRES_AGENDA_USER:-tt_agenda} WITH PASSWORD '${POSTGRES_AGENDA_PASSWORD:-tt_agenda_password}';
  CREATE DATABASE ${POSTGRES_AGENDA_DB:-tt_agenda} OWNER ${POSTGRES_AGENDA_USER:-tt_agenda};

  -- Attendance
  CREATE USER ${POSTGRES_ATTENDANCE_USER:-tt_attendance} WITH PASSWORD '${POSTGRES_ATTENDANCE_PASSWORD:-tt_attendance_password}';
  CREATE DATABASE ${POSTGRES_ATTENDANCE_DB:-tt_attendance} OWNER ${POSTGRES_ATTENDANCE_USER:-tt_attendance};

  -- Analytics
  CREATE USER ${POSTGRES_ANALYTICS_USER:-tt_analytics} WITH PASSWORD '${POSTGRES_ANALYTICS_PASSWORD:-tt_analytics_password}';
  CREATE DATABASE ${POSTGRES_ANALYTICS_DB:-tt_analytics} OWNER ${POSTGRES_ANALYTICS_USER:-tt_analytics};
EOSQL
