services:
  tt-infra:
    ports:
      - "${INFRA_PORT:-8084}:5000"

  tt-auth:
    ports:
      - "${AUTH_PORT:-8085}:5000"

  tt-members:
    ports:
      - "${MEMBERS_PORT:-8088}:5000"

  tt-agenda:
    ports:
      - "${AGENDA_PORT:-8086}:5000"

  tt-analytics:
    ports:
      - "${ANALYTICS_PORT:-8087}:5000"

  tt-attendance:
    ports:
      - "${ATTENDANCE_PORT:-8089}:5000"
